import turtle
t = turtle.Turtle()
t.speed(3)
turtle.bgcolor("black")
t.color("RED")
t.begin_fill()
t.left(140)
t.forward(180)
t.circle(-90, 200)
t.setheading(60)
t.circle(-90, 200)
t.forward(180)
t.end_fill()
t.hideturtle()
text = turtle.Turtle()
text.hideturtle()
text.color("white")
text.penup()
text.goto(0, 20) 
text.write("💋I LOVE YOU Anie😘", font=("Arial", 24, "bold"), align="center")

turtle.done()
